### Probar el endpoint de cobro (charge)
POST http://localhost:8081/charge
Content-Type: application/json

{
  "amount": 5000
}

### Crear un pago (POST)
POST http://localhost:8080/payments
Content-Type: application/json

{
  "amount": 5000
}

###

### Consultar los pagos (GET)
GET http://localhost:8080/payments